---
title: "Further Resources"
---

## R resources

### Getting Help

- [Google it!](http://lmgtfy.com/?q=R+Error+in+library+there+is+no+package+called): Try Googling generalized versions of any error messages you get. That is, remove text that is specific to your problem (names of variables, paths, datasets, etc.). You'd be surprised how many other people have probably had the same problem and solved it.
- [Google Group](https://groups.google.com/forum/#!forum/bioc-ggtree): Always search before asking, and make a [reproducible example](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb) if you want to get useful advice. This is a minimal example that allows others who are trying to help you to see the error themselves.
- Read package vignettes. For example, see the [ggtre Bioconductor page](https://bioconductor.org/packages/release/bioc/html/ggtree.html), scroll about halfway down to see the [ggtree introduction](https://bioconductor.org/packages/release/bioc/vignettes/ggtree/inst/doc/ggtree.html) vignette.

### General R Resources

- [TryR](http://tryr.codeschool.com/): An interactive, browser-based R tutor
- [Swirl](http://swirlstats.com/): An R package that teaches you R (_and statistics!_) from within R
- [Jenny Bryan's Stat 545 "Data wrangling, exploration, and analysis with R" course material](https://stat545-ubc.github.io/): An excellent resource for learning R, dplyr, and ggplot2
- [DataCamp's free introduction to R](https://www.datacamp.com/courses/free-introduction-to-r)
- [More DataCamp courses](https://www.datacamp.com/courses) (UVA's education benefits will cover these!).
- [RStudio's printable cheat sheets](https://www.rstudio.com/resources/cheatsheets/)
- [Rseek](http://rseek.org/): A custom Google search for R-related sites
- Bioconductor [vignettes](https://www.bioconductor.org/help/package-vignettes/), [workflows](https://www.bioconductor.org/help/workflows/), and [course/conference materials](https://www.bioconductor.org/help/course-materials/)

### dplyr resources

- [The dplyr vignette](https://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html)
- [A longer dplyr tutorial with video and code](http://www.dataschool.io/dplyr-tutorial-for-faster-data-manipulation-in-r/)
- [The dplyr tutorial from the HarvardX Biomedical Data Science MOOC](http://genomicsclass.github.io/book/pages/dplyr_tutorial.html)
- [A dplyr cheat sheet from RStudio](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)

### ggplot2 resources

- [The official ggplot2 documentation](http://docs.ggplot2.org/)
- [The ggplot2 book](http://amzn.to/1akjqsR), edition 1, by the developer, Hadley Wickham
- [New version of the ggplot2 book, freely available on GitHub](https://github.com/hadley/ggplot2-book)
- [The ggplot2 Google Group](https://groups.google.com/d/forum/ggplot2) (mailing list, support forum)
- [LearnR](http://learnr.wordpress.com/): A blog with a good number of posts describing how to reproduce various kind of plots using ggplot2
- [SO questions tagged with ggplot2](http://stackoverflow.com/questions/tagged/ggplot2)
- [A catalog of graphs made with ggplot2, complete with accompanying R code](http://shinyapps.stat.ubc.ca/r-graph-catalog/)
- [RStudio's ggplot2 cheat sheet](https://www.rstudio.com/wp-content/uploads/2015/05/ggplot2-cheatsheet.pdf)

### treeio resources

- [Importing trees with data](https://bioconductor.org/packages/release/bioc/vignettes/treeio/inst/doc/Importer.html)
- [Exporting trees with data](https://bioconductor.org/packages/release/bioc/vignettes/treeio/inst/doc/Exporter.html)

### ggtree resources

- [ggtree homepage](https://guangchuangyu.github.io/software/ggtree/)
- [The ggtree google group](https://groups.google.com/forum/#!forum/bioc-ggtree)
- [ggtree Introduction](https://bioconductor.org/packages/release/bioc/vignettes/ggtree/inst/doc/ggtree.html)
- [Tree Visualization](https://bioconductor.org/packages/release/bioc/vignettes/ggtree/inst/doc/treeVisualization.html)
- [Tree Manipulation](https://bioconductor.org/packages/release/bioc/vignettes/ggtree/inst/doc/treeManipulation.html)
- [Tree Annotation](https://bioconductor.org/packages/release/bioc/vignettes/ggtree/inst/doc/treeAnnotation.html)
- [Phylomoji](https://guangchuangyu.github.io/software/ggtree/vignettes/phylomoji.html)
