---
title: "BMB209 SDU 2019 Phylogenetic Tree Data Integration and Visualization Workshop"
output: 
  html_document:
    toc: yes
---

This workshop introduces Bioconductor packages, treeio and ggtree, for importing, linking, exporting and visualizing phylogenetic tree with heterogeneous associated data using the R statistical computing environment. 

```{r, include=FALSE}
library(knitr)
knitr::opts_chunk$set(message=FALSE, warning=FALSE, eval=TRUE, echo=FALSE)
suppressPackageStartupMessages(library(dplyr))
```

## General Information

<https://odinlister.sdu.dk/fagbesk/internkode/BMB209/en>

**_When_: Jan. 2019**

**_Where_: University of Southern Denmark, Odense**  



**_Instructor_: Guangchuang Yu**&nbsp;
<a href="mailto:guangchuangyu@gmail.com" target="_blank"><i class="fa fa-envelope"></i></a>
<a href="http://portal.smu.edu.cn/jcyxy/info/1084/2203.htm" target="_blank"><i class="fa fa-university"></i></a>
<a href="https://twitter.com/guangchuangyu" target="_blank"><i class="fa fa-twitter"></i></a>
<a href="https://github.com/GuangchuangYu/" target="_blank"><i class="fa fa-github"></i></a>
<a href="http://guangchuangyu.github.io" target="_blank"><i class="fa fa-rss"></i></a>  
<small>Guangchuang Yu, Ph.D. is faculty in the School of Basic Medical Science at the Southern Medical University.</small>

### About this workshop 

This workshop introduces Bioconductor packages, treeio and ggtree, for importing, linking, exporting and visualizing phylogenetic tree with heterogeneous associated data using the R statistical computing environment. Specifically, the course introduces the **treeio** package for parsing a number of software outputs that contain phylogenetic tree with evolutionary evidences, linking external data to the phylogenetic tree structure and exporting tree with data in a single file, and the **ggtree** package for visualizing and annotating phylogenetic tree with covariates and other associated data.


**This is not an R class.** Some general knowledge of the R language is helpful.

**This is not a _"How to build phylogenetic tree"_ class.** There are a number of upstream software, including IQ-tree and RAxML for building phylogenetic tree, BEAST and PAML for inferring evolutionary evidences. This course only cover **downstream** interpretation -- managing, manipulating, visualizing and analyzing phylogenetic associated data in evolutionary context. 

## Setup

**[Click the <i class="fa fa-cog"></i> Setup](setup.html) link on the navbar at the top and review all the information and follow the instructions _prior to the workshop_**.

You should set aside a couple hours to download, install, and test all the software needed for the course. All the software we're using in class is open-source and freely available online. This setup must be completed _prior to class_, as we will not have much time for troubleshooting software installation issues during class. 

After installing and testing the software we'll be using, please download the data as instructed, and review the required reading _prior to class_.



## FAQ

#### What are the pre-requisites?

[(There is some required reading and software setup required before the workshop)](setup.html). This class assume you have basic knowledge of the R programming language. If you don't have any experiecne, it would be helpful if you go through the [R Basic](r-basics.html), [Data Frames](r-dataframes.html) and [Data Visualization](r-viz-gapminder.html).


#### Do I need a laptop?

**_YES._** You must have access to a computer on which you can install software. The class will be a mix of lecture, discussion, but primarily live coding. You must bring your laptop to each session. Bring your charging cable also. Please follow the [setup instructions](setup.html) prior to the workshop.

#### Where do I get additional help?

Glad you asked! [See here](help.html).



----

<small>**_Attribution_:** Course material is inspired by and/or modified in part from [4-VA JMU 2017 Biological Data Science Workshop](https://4va.github.io/biodatasci/).</small>